theme: jekyll-theme-slate
# Site settings
title: w会是n的灯塔                   		
description: "有一分热，发一分光，就令萤火一般，也可以在黑暗里发一点光，不必等候炬火。"	   	   

# SNS settings      
github_username: whsndl    
qq_username: 3108719694

# Build settings
# paginate: 4             
 
# Sidebar settings
sidebar: true 
